os: linux

jobs:
  include:
    - arch: ppc64le
      dist: xenial
    - arch: ppc64le
      dist: bionic
    - arch: ppc64le
      dist: focal
    - arch: s390x
      dist: xenial
    - arch: s390x
      dist: bionic
    - arch: s390x
      dist: focal
      
script:
  - sudo apt update -y
  - sudo apt install -y tmate
  - tmate --version
